export const routerStub = {
  route: '',
  pathname: '',
  query: {},
  asPath: '',
  isFallback: false,
  basePath: '',
  locale: '',
  locales: [],
  defaultLocale: '',
  isReady: false,
  isPreview: false,
  isLocaleDomain: false,
  components: {},
  push: async () => {},
  replace: async () => {},
  prefetch: async () => {},
  beforePopState: async () => {},
  back: async () => {},
  reload: async () => {},
  events: {
    on: () => {},
    off: () => {},
    emit: () => {},
  },
};
